default: &default
  adapter: postgresql
  encoding: unicode
  host: "127.0.0.1"
  port: 5433
  username: postgres
  password: postgres
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: prog_image_development

test:
  <<: *default
  database: prog_image_test

production:
  <<: *default
  database: prog_image_production
  username: prog_image
  password: <%= ENV["PROG_IMAGE_DATABASE_PASSWORD"] %>
  port: 5432
